create table
  public.logs (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    content text null,
    user_id uuid not null,
    constraint logs_pkey primary key (id),
    constraint logs_user_id_fkey foreign key (user_id) references profiles (id) on delete cascade
  ) tablespace pg_default;